### ISSUE TITLE
`VarVsEffPlot`: Missing errorbar if preceding bin is `np.inf`/`np.nan`

### ISSUE THREAD

**Issue by joschkabirk** [umami-hep/puma#130]
When a rejection value is infinity (efficiency 0) in a `VarVsEffPlot`, the bin does not have an entry (this is fine I think - matplotlib ignores `np.inf` values by default).

However, with the current implementation, the uncertainty band of the subsequent bin is also affected/not shown as can be seen below.

<img width="540" alt="Screenshot 2022-09-20 at 09 52 12" src="https://user-images.githubusercontent.com/46069353/191199671-28b718b8-850d-418e-a4d3-2f5508405a32.png">

To reproduce:

Take the example script [`plot_pt_vs_eff.py
`](https://github.com/umami-hep/puma/blob/main/examples/plot_pt_vs_eff.py) and set the pt value of light jets to zero in the second-to last bin:

```py
pt_in_second_to_last_bin = np.logical_and(
    df["pt"].values / 1e3 > 140,
    df["pt"].values / 1e3 < 175,
)
pt[np.logical_and(pt_in_second_to_last_bin, is_light)] = 0
```

**Comment by dkobylianskii** [comment]
![pt_light_rej](https://github.com/umami-hep/puma/assets/7422741/7e32548d-6791-42e2-a6e0-329d39cf3a45)

As I can see, we don't have such a bug in the current implementation. Closing
