### ISSUE TITLE
Multiple backgrounds in one `Roc` or `VarVsEff`

### ISSUE THREAD

**Issue by zcapjdb** [umami-hep/puma#134]
The current implementation of `VarVsEff`  is to define a signal and background which is then plotted with `VarVsEffPlot` where you can choose to plot either the signal or background (similarly for `Roc`). This works fine with two classes but in most use cases we will want to look at a signal class (b-jets) and two different backgrounds (light and c-jets), which requires defining a minimum of two `VarVsEff` objects.

It would be nice if this could be made more flexible and we could define both backgrounds within the same object and then when plotting choose the signal or any of the backgrounds.

**Comment by samvanstroud** [comment]
@zcapjdb I guess this is just relevant for `VarVsEffPlot` right? Since we can plot multiple backgrounds on the same roc. Anyways I worry this might lead to difficult to read plots. If you want to work on it fine, otherwise I think probably having two plots is okay

**Comment by zcapjdb** [comment]
Wow, I long forgot about this. I think this was from pre high level API? So yeah this isn't as much an issue anymore
