### ISSUE TITLE
Follow-up for high level API

### ISSUE THREAD

**Issue by manuguth** [umami-hep/puma#140]
The high level API was introduced in https://github.com/umami-hep/puma/pull/128 and there were still some open points which need to be addressed but can be done in another pull request. This issue will keep track of these changes:

- [ ] The `Tagger` class can be interfaced with https://jsonargparse.readthedocs.io/
- [ ] `extract_tagger_scores` function in `Tagger` class: rather than a single source which cannot be type hinted and a source_type, I would suggest to have df : DataFrame = None and path: Path = None arguments and the logic can be based on which of the two is defined. (see [comment](https://github.com/umami-hep/puma/pull/128#discussion_r1029156134))
- [x] making `self.scores` in `Tagger` class a pandas data frame (see [comment](https://github.com/umami-hep/puma/pull/128#discussion_r1029171018))
- [ ]  `extract_tagger_scores` function should dynamically set self.is_light etc based on the passed/loaded jets (see [comment](https://github.com/umami-hep/puma/pull/128#discussion_r1029173055))
- [x] add fc scan curves

**Comment by samvanstroud** [comment]
Also we should extend the support beyond b/c signal jets, e.g. to the Xbb use case where we have VHbb/cc signal jets and then VHcc/bb, top, qcd backgrounds
