### ISSUE TITLE
Hatching in `puma.Histogram` uncertainties not rendered in AdobeAcrobat

### ISSUE THREAD

**Issue by joschkabirk** [umami-hep/puma#144]
AdobeAcrobat seems to not properly render the hatching we use for the stat. uncertainties in the histogram plots.

See issue [here](https://github.com/matplotlib/matplotlib/issues/12367).

<img width="990" alt="image" src="https://user-images.githubusercontent.com/46069353/206999438-1857a8a3-d10d-46d7-bf66-2a86278f4023.png">

This might be an Issue of AdobeAcrobat, but still we might want to make this more robust to avoid this problem?

We could

a) Use the same style as we already do in e.g. the `VarVsEff` plots, where the uncertainty is a coloured band around the line (in the same colour as the line but with `alpha < 1`) This could also help with the ratio uncertainties, since they are rather hard to read atm I would say

b) Same as a), but using the same colour in all cases, e.g. always display the stat. uncertainty as a transparent grey band

c) something else

**Comment by dkobylianskii** [comment]
Hatching is replaced with filling, so we can close this.
