### ISSUE TITLE
plot_base ratio axis limits bug

### ISSUE THREAD

**Issue by samvanstroud** [umami-hep/puma#174]
These are set as `None` in the [`__post_init__`](https://github.com/umami-hep/puma/blob/main/puma/plot_base.py#L212) regardless of what is passed to the constructor. 

As a workaround it's possible to directly set the limits
```
plot.ratio_axes[0].set_ylim(bottom=ymin, top=ymax)
```

We can either:
- fix the bug in the post init so the ratio limits can be set in the constructor
- remove the ratio axis limits entirely from the constructor, and also remove [`set_y_lim`](https://github.com/umami-hep/puma/blob/main/puma/plot_base.py#L428) and instead set them directly as above. this is potentially nicer as we work directly with the underlying matplotlib objects rather than writing functions with interface with them

**Comment by dkobylianskii** [comment]
I suggest to fix the bug now (#175). Then we can think more.\
From my side, I prefer to have a user-friendly interface and not push users to check how we define ratio plots to call mpl's `set_ylim`.

**Comment by samvanstroud** [comment]
Many thanks @dkobylianskii, sounds good to me.
