### ISSUE TITLE
Changing label for Hbb and Hcc

### ISSUE THREAD

**Issue by afroch** [umami-hep/puma#185]
Maybe we could change the legend label of Hbb and Hcc, which are currently set to be `$Hbb$-jets` and `$Hcc$-jets` to something like `$H \rightarrow b\bar{b}$-jets` and `$H \rightarrow c\bar{c}$-jets`? 

Not sure if we want this, but it seems to me a bit cleaner.

Tagging @samvanstroud @philippgadow for discussion

**Comment by philippgadow** [comment]
good idea! I agree, it would look much cleaner.

**Comment by samvanstroud** [comment]
I guess this is more for the tools package, right? the labels are defined here https://github.com/umami-hep/atlas-ftag-tools/blob/main/ftag/flavours.yaml

**Comment by afroch** [comment]
Yeah, it's a general thing that I will need to add in the atlas-ftag-tools and from there process the change down to all other packages

**Comment by samvanstroud** [comment]
Why would you have to change the downstream packages? Aren't they pullling thte definitions from the tools package already?

**Comment by afroch** [comment]
We need to update the version in the other packages of atlas-ftag-tools. That's what i meant. sorry for the confusion
