### ISSUE TITLE
Adding Documentation for Data/MC Plot

### ISSUE THREAD

**Issue by afroch** [umami-hep/puma#189]
Hmm maybe I should have asked to update this docs [here](https://umami-hep.github.io/puma/main/examples/histograms.html#more-general-example) before merging. Can you do this in a follow up MR @afroch?

_Originally posted by @samvanstroud in https://github.com/umami-hep/puma/issues/187#issuecomment-1602239299_

**Comment by samvanstroud** [comment]
Friendly ping @afroch on this one
