### ISSUE TITLE
more efficient ROC curves with weights

### ISSUE THREAD

**Issue by dguest** [umami-hep/puma#197]
I might be misreading the code, but [the way the ROC efficiency is calculated][1] seems:

1. Inefficient
2. Unusable if there are weights

The inefficiency comes from code of the form 

```python
for i,threshold in enumerate(thresholds):
    eff[i] = len(scores > threshold) / len(scores)
```

which requires N passes for N thresholds. This could be replaced by something more like

```python
hist, edges = np.histogram(scores, thresholds)
eff = hist[::-1].cumsum()[::-1] / hist.sum()
```

which calculates the same thing in a single pass.

Both implementations could be extended to support weights, but unfortunately I don't think [np.percentile][per] could. Anyway, percentile could be replaced with an interpolation over the `edges` array, as a function of `eff`.

[1]: https://github.com/umami-hep/puma/blob/main/puma/metrics.py#L51
[per]: https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

**Comment by samvanstroud** [comment]
Thanks @dguest! `np.percentile` is currently used to calculate the disc thresholds from the target effs, so I would extend your example to
```python
xs = np.linspace(0.5, 1.0, 100)
thresholds = np.percentile(sig_disc, xs)
hist, edges = np.histogram(scores, thresholds)
eff = hist[::-1].cumsum()[::-1] / hist.sum()
```
I think this would still support weights. 

@dkobylianskii do you have some time to take a look at this one? If not I can get to it next week :)

**Comment by dguest** [comment]
Sorry I'm probably being slow: how does this support weights? Doesn't `np.percentile` find the value of `sig_disc` that is greater than `xs` of the full array? How are the individual points in the array weighted? My suggestion was to use the weighted histogram integral to find the point where the cumulative distribution passes `xs` (which is just using interpolation where the x axis is the cumulative efficiency array and the y axis is the edge value).

**Comment by samvanstroud** [comment]
Ah good point, we need to apply the weights when calcuting the thresholds, not just when computing the efficiencies from these. I overlooked that.

So we can go straight from disc cuts to effs, nice!

**Comment by samvanstroud** [comment]
Close by #206
