### ISSUE TITLE
Issue with histogram ratio uncertainties

### ISSUE THREAD

**Issue by samvanstroud** [umami-hep/puma#213]
we compute the [uncertainty on the ratio](https://github.com/umami-hep/puma/blob/f94afad06eb10f3d87c86a03e37edb1269be6592/puma/utils/histogram.py#L224) for the ratio plots, but we plot uncertainties for both the ratio and the denominator hits. 

For the uncertainty bands in the ratio plots, I think we should either:
- plot the uncertainty on the numerator and denominator separately (two bands)
- plot a sinlge band of the error on the ratio and leave the line at y=1 without an uncertainty.

cc @nikitapond

**Comment by afroch** [comment]
I think the "usual" ATLAS way to do this is with two bands, no?

**Comment by samvanstroud** [comment]
Two bands is fine, but then we should not plot the uncertainty on the ratio right? but just the same uncertainty as on the top panel.

**Comment by samvanstroud** [comment]
@afroch do you agree here? tagging also @dkobylianskii

**Comment by afroch** [comment]
Not sure what you mean with not plotting the uncertainty on the ratio tbh.. My suggestion would be to plot the uncertainty on the numerator and denominator separately as you suggested. Therefore, multiple lines can be plotted into one plot and the ratio still has the correct uncertainties (although it will be quite messy).

**Comment by afroch** [comment]
Let's say the reference is 175 +- 10 and the second line is 185 +- 15. I would simply normalise it to reference

For the reference line:
central value: 175 / 175 = 1
uncertainty: 10 / 175 = 0.057......

For the line we want to compare:
central value: 185 / 175 = 1.057.....
uncertainty: 15 / 175 = 0.0857....

And now simply plot these values. Not sure if this is the correct way tbh.. brain is a bit damaged atm. due to writing a thesis 😅

**Comment by samvanstroud** [comment]
Yes I would have agreed, but atm we sum the two uncertainties from the numberator and denominator in quadrature [here](https://github.com/umami-hep/puma/blob/f94afad06eb10f3d87c86a03e37edb1269be6592/puma/utils/histogram.py#L224).

**Comment by nhartman94** [comment]
Agree w/ you @samvanstroud at not summing the the two uncertainties from the numberator and denominator in quadrature and I agree @ keeping as two separate lines :)

**Comment by samvanstroud** [comment]
@dkobylianskii would you have time to implement a fix for this one?

**Comment by samvanstroud** [comment]
@dkobylianskii I'm reopening this, I noticed in our ROCs that we have an uncertainty on the denominator in the ratio panel, but I think we need to remove this.

cc @AndriusVaitkus97

**Comment by samvanstroud** [comment]
I discussed with @dguest who suggested we should not be combining uncertainties for the ratio since the uncertainties are not statistically independent. In that case we agreed to just show the uncertainty on each of the curves in the ratio panel, but to make sure we are not combining the uncertaintines for the line deviating from 1. @dkobylianskii do you agree here?

We should fix this and update the plots in the algo paper at some point.

**Comment by dkobylianskii** [comment]
Hi @samvanstroud,
I agree, I will update plotting soon

**Comment by dkobylianskii** [comment]
I've checked, it's already working as expected
See https://github.com/umami-hep/puma/blob/main/puma/roc.py#L143

Closing :)
