### ISSUE TITLE
Add development guidelines

### ISSUE THREAD

**Issue by jobirk** [umami-hep/puma#25]
We should add some development guidelines to the puma docs.
Let's use this issue to collect what we want to add

- [x] Link to Docker images + commands that can be used to start a container for usage and development
- [x] Quick summary on how artifacts of WIP docs can be downloaded for review (non-`main` commits upload the docs as an artifact, which can be downloaded as a zip file)

tagging @philippgadow @afroch @manuguth

**Comment by afroch** [comment]
Maybe also adding the development guides we have in Umami? With the VSCode setup and the linter explained etc.?
