### ISSUE TITLE
Sphinx documentation

### ISSUE THREAD

**Issue by manuguth** [umami-hep/puma#3]
After adding sphinx in the pipeline we need to also do the following 

- [ ] making sure that functions also in `__init__.py` are properly handled
- [x] Adding tutorials and examples
- [x] version/tag support (#42 , #45)
- [x] add pipeline status (does this exist for GitHub?)
- [x] Fix `**kwargs` docstring for cases where it is not nicely displayed in the docs ([e.g. `puma.VarVsEff`](https://umami-hep.github.io/puma/autoapi/puma/var_vs_eff/index.html#puma.var_vs_eff.VarVsEff))

**Comment by jobirk** [comment]
Hi @manuguth @afroch 
I had another look at other projects that use GitHub pages for the deployment of their documentation.

I think it would be better to have the `gh-pages` branch independent of the `main` branch.
This way we can just put the documentation there using [this workflow](https://github.com/marketplace/actions/deploy-to-github-pages).

This has the following advantages:
- the `gh-pages` branch only stores the code relevat for the actual deployment
- the deployment is only refreshed if the documentation changes (i.e. for commits on `main` that don't affect the documentation, there is no commit on the `gh-pages` branch)

<img width="572" alt="image" src="https://user-images.githubusercontent.com/46069353/167365193-6a484bcb-b1d1-485f-b824-318085432e2f.png">

I tried this for an [old project of mine](https://github.com/jobirk/panim) and it seems to work quite nicely.

If you agree I'll adapt to this method here as well.

**Comment by manuguth** [comment]
I agree, this workflow looks good.

how would you decide what triggers the docs CI or not?

this would be easy if we would simply have static docs, but since sphinxs evaluates all the doc strings, the function arguments etc. I would say it's difficult to decide when to run this action and when not to.

Always running it would be the easiest I guess

**Comment by jobirk** [comment]
Yeah I would always run it.

So the docs are built for every commit on `main`, but the workflow checks if the resulting docs are changed.
In the (rather rare) case of a commit that doesn't affect the docs, the workflow will just pass without comitting to the `gh-pages` branch.
