### ISSUE TITLE
Adding more parameters

### ISSUE THREAD

**Issue by afroch** [umami-hep/puma#31]
Currently, it is not possible to set a `ratio_cut` for the ROC plots. To further enhance puma, the following settings should be added. Also the documentation should be updated with all possible options.

* [X] `ratio_cut`: Give lower and upper y-limit of the ratio panels for ROC comparison.
* [ ] `fontsize_ticks`: Set the fontsize of the axis (like 0.60, 0.70 etc. for the ROC's).
* [x] `flavour_legend_position`: Position of the flavour legend in the ROC comparison plots.

Is related to [Umami Issue 153](https://gitlab.cern.ch/atlas-flavor-tagging-tools/algorithms/umami/-/issues/153)

**Comment by jobirk** [comment]
`ratio_cut` is already included as `ymin_ratio_1`, `ymax_ratio_1`, `ymin_ratio_2`, `ymax_ratio_2`

**Comment by afroch** [comment]
Ah yeah that's right!
