### ISSUE TITLE
Change default number of ratio panels to 0 for histogram plots

### ISSUE THREAD

**Issue by jobirk** [umami-hep/puma#4]
With the current implementation, the default value of `n_ratio_panels` is 1 for histogram plots.
This means that (quick) plotting without a ratio requires you to specifically set `n_ratio_panels=0`.

I think it should be the other way around, especially since the code raises an error if `n_ratio_panels=1` but no reference histogram is defined. This is annoying when you simple histogram plot with as few lines as possible.

I'll change that as soon as we migrated the code to this repo.

**Comment by afroch** [comment]
I would also suggest to change that globally for all plots. Because, for example, the `fraction_scan` plots do not need a ratio panel.

**Comment by jobirk** [comment]
Yeah I agree.
Also also for the ROC curves I think it's fine to specifically define it if needed.

I'll change it in **PlotObject** then.

What do you think @manuguth ?

**Comment by afroch** [comment]
Could we, for the roc, make that somehow dependent on how many lines you have defined?

**Comment by manuguth** [comment]
> 

I would not do that, that's something we can do in umami, but the api should be as clean as possible, where the user should define everything
