### ISSUE TITLE
add more colours

### ISSUE THREAD

**Issue by philippgadow** [umami-hep/puma#98]
The colour palette provided in [`get_good_colours()`](https://github.com/umami-hep/puma/blob/59d4bcffe1d9938515a88e731fc4bec937eae34e/puma/utils/__init__.py#L111) only provides 6 colours and could be extended or could be outsourced to [`palettable`](https://jiffyclub.github.io/palettable/).

**Comment by manuguth** [comment]
Looking for instance at [dark2_8](https://jiffyclub.github.io/palettable/colorbrewer/qualitative/#dark2_8) from [`palettable`](https://jiffyclub.github.io/palettable/) they also only have 8 colours.

we could extend our default colours and add on top a colour scheme option from `palettable`

**Comment by dkobylianskii** [comment]
It seems that 14 colors are enough for now. Closing.
